<?php
/** Page cohorts, retention and navigation checks; disposable fixtures only. */
if(!defined('GTLM_TEST_FIXTURE')||!GTLM_TEST_FIXTURE||!str_starts_with(DB_NAME,'gtlm_test_'))exit(2);
require_once GTLM_PATH.'includes/class-gtlm-analytics.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-controller.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-view.php';require_once GTLM_PATH.'includes/class-gt-link-import.php';require_once GTLM_PATH.'includes/class-gt-link-admin-pages.php';require_once GTLM_PATH.'includes/class-gt-link-admin.php';require_once GTLM_PATH.'includes/class-gt-link-list-table.php';require_once ABSPATH.'wp-admin/includes/template.php';require_once ABSPATH.'wp-admin/includes/screen.php';
$checks=[];function drill_check($ok,$label,$details=null){global$checks;$checks[]=['ok'=>(bool)$ok,'check'=>$label,'details'=>$ok?null:$details];}
$db=new GTLM_Analytics_DB();$s=GTLM_Settings::get_instance();global$wpdb;GTLM_Analytics::delete();GTLM_Analytics::enable();$gen=GTLM_Analytics::config()['generation'];$a='https://source.example.org/article%20one/';$b='https://source.example.org/article-two/';
$one=$db->insert_link(['name'=>'First target','slug'=>'drill-one','url'=>home_url('/target-one')]);$two=$db->insert_link(['name'=>'Second target','slug'=>'drill-two','url'=>home_url('/target-two')]);
function drill_event($id,$page,$country,$device){global$db,$gen;$event=['link_id'=>$id,'occurred_at'=>gmdate('Y-m-d H:i:s'),'generation'=>$gen,'source'=>'source.example.org','page'=>$page,'country'=>$country,'device'=>$device,'browser'=>'chrome','os'=>'linux','campaign'=>0,'status'=>302,'mode'=>'standard','geo'=>'off'];$db->append($event);return $event;}
// Rebuild schema 2, including already-processed records, so migration/backfill are real.
$wpdb->query('ALTER TABLE '.GTLM_Analytics_DB::hourly_table().' DROP PRIMARY KEY, DROP INDEX page_date, DROP COLUMN page_key, ADD PRIMARY KEY(link_id,bucket_start,dimension,value)');$wpdb->query('ALTER TABLE '.GTLM_Analytics_DB::events_table().' DROP INDEX page_pending, DROP COLUMN page_processed');$c=GTLM_Analytics::config();$c['schema']='2';update_option('gtlm_analytics',$c,false);
foreach([[$one,$a,'IN','desktop'],[$one,$a,'IN','desktop'],[$two,$a,'US','mobile'],[$one,$b,'FR','tablet']] as $args){$e=drill_event(...$args);foreach(GTLM_Analytics_DB::DIMENSIONS as $dim){$value=$dim==='total'?'':(string)$e[$dim];$wpdb->query($wpdb->prepare('INSERT INTO '.GTLM_Analytics_DB::hourly_table().' (link_id,bucket_start,dimension,value,clicks) VALUES(%d,%s,%s,%s,1) ON DUPLICATE KEY UPDATE clicks=clicks+1',$e['link_id'],substr($e['occurred_at'],0,16).':00',$dim,$value));}}$wpdb->query('UPDATE '.GTLM_Analytics_DB::events_table().' SET processed=1');
$r=GTLM_Analytics::upgrade();drill_check(!is_wp_error($r)&&GTLM_Analytics::config()['schema']===GTLM_Analytics::SCHEMA&&GTLM_Analytics::config()['generation']===$gen,'Schema 2 upgrades without changing generation');GTLM_Analytics::process();GTLM_Analytics::process();
$all=GTLM_Analytics_Controller::report([]);$r=GTLM_Analytics_Controller::report(['referrer'=>$a,'dimension'=>'country']);drill_check($all['total']===4&&$r['total']===3&&count($r['links'])===2,'Page filtering retains exact link totals without doubling global totals',$r);
$values=array_column($r['breakdown'],'clicks','value');drill_check((int)($values['IN']??0)===2&&(int)($values['US']??0)===1&&!isset($values['FR'])&&$r['details_unavailable']===0,'Retained records backfill countries for the correct page only',$values);
$r=GTLM_Analytics_Controller::report(['referrer'=>$a,'link_id'=>$one,'dimension'=>'device']);drill_check($r['total']===2&&count($r['links'])===1&&$r['breakdown']===[['value'=>'desktop','clicks'=>'2']],'Link drilldown preserves its referring-page cohort',$r);
// A discarded generation must never enter page details, even with an existing same-minute page bucket.
$bad=drill_event($one,$a,'DE','unknown');$wpdb->query('UPDATE '.GTLM_Analytics_DB::events_table()." SET generation='retired' WHERE id=".(int)$wpdb->insert_id);GTLM_Analytics::process();$r=GTLM_Analytics_Controller::report(['referrer'=>$a,'dimension'=>'country']);drill_check(!in_array('DE',array_column($r['breakdown'],'value'),true)&&$r['total']===3,'Discarded events do not contaminate page cohorts');
// Losing old raw records cannot erase known totals or pretend the missing details are site-wide stats.
$wpdb->query($wpdb->prepare('DELETE FROM '.GTLM_Analytics_DB::hourly_table()." WHERE page_key=%s AND link_id=%d",hash('sha256',$a),$two));$wpdb->query($wpdb->prepare('DELETE FROM '.GTLM_Analytics_DB::events_table().' WHERE link_id=%d',$two));$r=GTLM_Analytics_Controller::report(['referrer'=>$a,'dimension'=>'country']);drill_check($r['total']===3&&$r['details_unavailable']===1&&in_array('_not_recorded',array_column($r['breakdown'],'value'),true),'Historical detail gaps are explicit while page counts survive');
$f=GTLM_Analytics_Controller::filters(['referrer'=>$a]);$db->start_export();$rows=$db->export_page($f,[]);$db->finish_export();drill_check(count($rows)>0&&count(array_filter($rows,fn($row)=>$row['page_key']!==hash('sha256',$a)&&!($row['page_key']===''&&$row['dimension']==='page'&&$row['value']===$a)))===0,'Filtered export contains only the selected page');
foreach([['array'],'javascript:alert(1)','https://example.org/?secret=x','https://example.org/'.str_repeat('x',1025)] as $invalid){drill_check(is_wp_error(GTLM_Analytics_Controller::filters(['referrer'=>$invalid])),'Invalid referring-page filter rejected');}
// Forever applies only to summaries. Historical windows remain bounded to 90 days per request.
$r=GTLM_Analytics::configure(['summary_days'=>0],true);drill_check(!is_wp_error($r)&&GTLM_Analytics::config()['summary_days']===0,'Forever is saved explicitly');$old=gmdate('Y-m-d H:i:s',time()-400*DAY_IN_SECONDS);$wpdb->query($wpdb->prepare('INSERT INTO '.GTLM_Analytics_DB::hourly_table()." (link_id,bucket_start,dimension,value,clicks) VALUES(%d,%s,'total','',9)",$one,$old));$wpdb->query($wpdb->prepare('UPDATE '.GTLM_Analytics_DB::events_table().' SET occurred_at=%s',$old));$db->prune(7,0);drill_check((int)$wpdb->get_var($wpdb->prepare('SELECT SUM(clicks) FROM '.GTLM_Analytics_DB::hourly_table().' WHERE bucket_start=%s',$old))===9&&(int)$wpdb->get_var('SELECT COUNT(*) FROM '.GTLM_Analytics_DB::events_table())===0,'Forever preserves old summaries while raw events expire');
$date=wp_date('Y-m-d',strtotime($old.' UTC'));$r=GTLM_Analytics_Controller::report(['from'=>$date,'to'=>$date,'link_id'=>$one]);drill_check(!is_wp_error($r)&&$r['total']===9,'Old retained reports are accessible through a bounded date range');$db->prune(7,90);drill_check((int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.GTLM_Analytics_DB::hourly_table().' WHERE bucket_start=%s',$old))===0,'Finite retention resumes normal pruning');
// Rendered links preserve page identity and filters; settings no longer require expanding sections.
wp_set_current_user(1);$_GET=['referrer'=>$a,'dimension'=>'country','period'=>'7'];ob_start();GTLM_Analytics_View::render();$html=ob_get_clean();drill_check(str_contains($html,'Links clicked from this page')&&str_contains($html,'name="referrer"')&&str_contains($html,'nav-tab-active')&&substr_count($html,'id="gtlm-breakdown"')===1,'Page context and native tabs render without duplicate IDs');
$url_method=(new ReflectionClass(GTLM_Analytics_View::class))->getMethod('report_url');$url=$url_method->invoke(null,['referrer'=>$a,'dimension'=>'country'],admin_url('admin.php?page=gtlm-links-analytics'));parse_str(wp_parse_url($url,PHP_URL_QUERY),$query);drill_check($query['referrer']===$a&&GTLM_Analytics_Controller::report($query)['total']===3,'Encoded referring URLs survive navigation query parsing');
$_GET=['view'=>'settings'];ob_start();GTLM_Analytics_View::render();$html=ob_get_clean();drill_check(!str_contains($html,'<details')&&str_contains($html,'>Forever</option>')&&str_contains($html,'type="text" class="regular-text"'),'All analytics settings are visible and text fields use native input types');
$table=new GTLM_List_Table(new GTLM_DB(),[],$s->prefix(),'');$method=(new ReflectionClass($table))->getMethod('column_total_clicks');$s->update(array_merge($s->all(),['enable_click_tracking'=>1]));$item=$db->get_link_by_id($one);$item['total_clicks']=7;drill_check(str_contains($method->invoke($table,$item),'link_id='.$one),'Enabled analytics makes lifetime counts clickable');$geo=(new ReflectionClass($table))->getMethod('column_geo');drill_check(str_contains($geo->invoke($table,['geo_mode'=>'off']),'>N/A</span>'),'No geo rules renders an N/A badge');wp_set_current_user(0);drill_check(!str_contains($method->invoke($table,$item),'<a'),'Analytics count links respect capabilities');
GTLM_Analytics::delete();$db->delete_link($one);$db->delete_link($two);$out=['passed'=>count(array_filter($checks,fn($c)=>$c['ok'])),'checks'=>$checks,'failed'=>array_values(array_filter($checks,fn($c)=>!$c['ok']))];echo json_encode($out,JSON_PRETTY_PRINT);exit($out['failed']?1:0);
