<?php
if(!defined('GTLM_TEST_FIXTURE')||!GTLM_TEST_FIXTURE||!str_starts_with(DB_NAME,'gtlm_test_'))exit(2);
require_once GTLM_PATH.'includes/class-gtlm-analytics.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-collector.php';
$checks=[];function fail_check($ok,$label,$detail=null){global$checks;$checks[]=['ok'=>(bool)$ok,'check'=>$label,'details'=>$ok?null:$detail];}
GTLM_Analytics::delete();$s=GTLM_Settings::get_instance();$db=new GTLM_Analytics_DB();global$wpdb;
$old=$wpdb->suppress_errors(true);$filter=function($sql){return str_contains($sql,'CREATE TABLE '.GTLM_Analytics_DB::hourly_table())?'INVALID_DDL':$sql;};add_filter('query',$filter);$r=GTLM_Analytics::enable();remove_filter('query',$filter);$wpdb->suppress_errors($old);fail_check(is_wp_error($r)&&!$s->advanced_analytics_enabled()&&!get_option('gtlm_analytics',false),'Partial schema failure stays off without config');GTLM_Analytics::delete();$r=GTLM_Analytics::enable();fail_check(!is_wp_error($r),'Partial setup cleanup and retry succeeds');
$id=$db->insert_link(['name'=>'Failure fixture','slug'=>'failure-fixture','url'=>home_url('/target')]);$link=$db->get_link_by_id($id);wp_set_current_user(0);$_SERVER['REQUEST_METHOD']='GET';$_SERVER['HTTP_USER_AGENT']='Mozilla/5.0 Safari';$_SERVER['HTTP_REFERER']='https://fixture.example.org/private-secret';GTLM_Analytics_Collector::collect($link,302,null);
$old=$wpdb->suppress_errors(true);$filter=function($sql){return str_starts_with($sql,'INSERT INTO '.GTLM_Analytics_DB::hourly_table())?'INVALID_AGGREGATION':$sql;};add_filter('query',$filter);$r=GTLM_Analytics::process();remove_filter('query',$filter);$wpdb->suppress_errors($old);fail_check(is_wp_error($r),'Aggregation failure reported');fail_check((int)$wpdb->get_var('SELECT COUNT(*) FROM '.GTLM_Analytics_DB::events_table().' WHERE processed=0')===1&&(int)$wpdb->get_var('SELECT COUNT(*) FROM '.GTLM_Analytics_DB::hourly_table())===0,'Failed aggregation rolls back both sides');GTLM_Analytics::process();fail_check((int)$wpdb->get_var("SELECT SUM(clicks) FROM ".GTLM_Analytics_DB::hourly_table()." WHERE dimension='total'")===1,'Retry after rollback counts once');
$event=$wpdb->get_row('SELECT * FROM '.GTLM_Analytics_DB::events_table().' LIMIT 1',ARRAY_A);unset($event['id'],$event['processed']);$event['occurred_at']=gmdate('Y-m-d H:i:s',time()-8*86400);$db->append($event);GTLM_Analytics::process();fail_check(GTLM_Analytics::config()['expired_pending']>=1,'Expired unprocessed records create a gap indicator');
$other=new mysqli(DB_HOST,DB_USER,DB_PASSWORD,DB_NAME);$key='gtlm:'.md5(DB_NAME.':'.$wpdb->prefix);$other->query("SELECT GET_LOCK('".$other->real_escape_string($key)."',0)");$r=GTLM_Analytics::process();fail_check(is_wp_error($r)&&$r->get_error_code()==='gtlm_analytics_busy','Concurrent worker lock is nonblocking');$other->query("SELECT RELEASE_LOCK('".$other->real_escape_string($key)."')");$other->close();
$config=GTLM_Analytics::config();$config['lease_until']=time()+900;$config['state']='active';$config['exclude_links']=[$id];update_option('gtlm_analytics',$config,false);fail_check(!GTLM_Analytics_Collector::collect($link,302,null),'Per-link exclusion prevents append');
GTLM_Deactivator::deactivate();fail_check(!$s->advanced_analytics_enabled()&&!wp_next_scheduled('gtlm_analytics_maintenance'),'Deactivation pauses and unschedules');GTLM_Activator::activate();fail_check(!$s->advanced_analytics_enabled()&&(bool)wp_next_scheduled('gtlm_analytics_maintenance'),'Reactivation resumes retention without collection');
GTLM_Analytics::enable(['exclude_links'=>[]]);$event['occurred_at']=gmdate('Y-m-d H:i:s');$event['generation']='retiredgeneration0000000000000000';$db->append($event);$before=(int)$wpdb->get_var("SELECT SUM(clicks) FROM ".GTLM_Analytics_DB::hourly_table()." WHERE dimension='total'");GTLM_Analytics::process();fail_check((int)$wpdb->get_var("SELECT SUM(clicks) FROM ".GTLM_Analytics_DB::hourly_table()." WHERE dimension='total'")===$before,'Retired generation cannot reappear after resume');
$db->delete_link($id);GTLM_Analytics::process();fail_check((int)$wpdb->get_var('SELECT COUNT(*) FROM '.GTLM_Analytics_DB::hourly_table().' WHERE link_id='.(int)$id)===0,'Permanent link deletion removes summaries');
GTLM_Analytics::delete();$out=['passed'=>count(array_filter($checks,fn($c)=>$c['ok'])),'checks'=>$checks,'failed'=>array_values(array_filter($checks,fn($c)=>!$c['ok']))];echo json_encode($out,JSON_PRETTY_PRINT);exit($out['failed']?1:0);
