<?php
/** Referring-page capture, upgrade and report checks on an isolated fixture only. */
if(!defined('GTLM_TEST_FIXTURE')||!GTLM_TEST_FIXTURE||!str_starts_with(DB_NAME,'gtlm_test_'))exit(2);
require_once GTLM_PATH.'includes/class-gtlm-analytics.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-collector.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-controller.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-referrer.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-view.php';
$checks=[];function page_check($ok,$label,$data=null){global$checks;$checks[]=['ok'=>(bool)$ok,'check'=>$label,'details'=>$ok?null:$data];}
$db=new GTLM_Analytics_DB();$settings=GTLM_Settings::get_instance();global$wpdb;GTLM_Analytics::delete();GTLM_Analytics::upgrade();page_check(!$settings->analytics_initialized()&&!get_option('gtlm_analytics',false)&&!$wpdb->get_col("SHOW TABLES LIKE '%gtlm_analytics%'"),'Upgrade does not create analytics before opt-in');
$cases=[
 ['https://EXAMPLE.org:443/article/?token=private#section','example.org','https://example.org/article/'],
 ['http://example.org:8080/a%20b','example.org','http://example.org:8080/a%20b'],
 ['https://example.org/परीक्षण/','example.org','https://example.org/'.rawurlencode('परीक्षण').'/'],
 ['https://example.org','example.org','https://example.org/'],
 ['https://example.org/?p=123&token=private','example.org',''],
 ['https://example.org/wp-admin/post.php?post=123','example.org',''],
 ['https://example.org/%77p-login.php','example.org',''],
 ['https://name:secret@example.org/post/','',''],['javascript:alert(1)','',''],['https://127.0.0.1/post/','',''],['https://example.org/a%0Db','example.org',''],['https://example.org/'.str_repeat('x',1010),'example.org',''],
];
foreach($cases as [$raw,$source,$page]){$r=GTLM_Analytics_Referrer::parse($raw);page_check($r===['source'=>$source,'page'=>$page],'Normalize referrer '.substr($raw,0,60),$r);}
GTLM_Analytics::enable();$id=$db->insert_link(['name'=>'Referrer fixture','slug'=>'referrer-fixture','url'=>home_url('/target')]);$link=$db->get_link_by_id($id);$generation=GTLM_Analytics::config()['generation'];
// Reconstruct actual schema 1, then collect with the new code before its control-plane migration.
$wpdb->query('ALTER TABLE '.GTLM_Analytics_DB::events_table().' DROP COLUMN page');$wpdb->query('ALTER TABLE '.GTLM_Analytics_DB::hourly_table()." MODIFY value varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT ''");$config=GTLM_Analytics::config();$config['schema']='1';unset($config['pages_started_at']);update_option('gtlm_analytics',$config,false);
wp_set_current_user(0);$_SERVER['REQUEST_METHOD']='GET';$_SERVER['HTTP_USER_AGENT']='Mozilla/5.0 Chrome/130 Safari';$_SERVER['HTTP_REFERER']='https://source.example.org/before/?secret=never';$_GET=[];
page_check(GTLM_Analytics_Collector::collect($link,302,null),'Schema-1 in-flight click survives before upgrade');
GTLM_Analytics::pause();$quiet=$wpdb->suppress_errors(true);$deny=static fn($sql)=>str_starts_with($sql,'ALTER TABLE '.GTLM_Analytics_DB::events_table())?'INVALID_MIGRATION_SQL':$sql;add_filter('query',$deny);$failed_upgrade=GTLM_Analytics::upgrade();remove_filter('query',$deny);$wpdb->suppress_errors($quiet);page_check(is_wp_error($failed_upgrade)&&GTLM_Analytics::config()['schema']==='1'&&GTLM_Analytics::config()['generation']===$generation,'Failed migration retains the old schema marker and history');$r=GTLM_Analytics::upgrade();page_check(!is_wp_error($r)&&GTLM_Analytics::config()['schema']==='2'&&GTLM_Analytics::config()['generation']===$generation&&!$settings->advanced_analytics_enabled(),'Migration preserves generation and paused consent');GTLM_Analytics::process();
$r=GTLM_Analytics_Controller::report(['link_id'=>$id]);page_check($r['total']===1&&$r['pages']===[['value'=>'','clicks'=>'1']],'Pre-upgrade click reports as page unavailable',$r['pages']);
GTLM_Analytics::enable();$c=GTLM_Analytics::config();$c['schema']='1';update_option('gtlm_analytics',$c,false);GTLM_Analytics::upgrade();page_check($settings->advanced_analytics_enabled()&&GTLM_Analytics::config()['generation']===$c['generation'],'Idempotent upgrade preserves an active generation');$_SERVER['HTTP_REFERER']='https://source.example.org/first%20post/?email=private@example.org#secret';$q=$wpdb->num_queries;page_check(GTLM_Analytics_Collector::collect($link,302,null)&&$wpdb->num_queries-$q<=2,'Page collector keeps one-insert query budget',$wpdb->num_queries-$q);
$e=$wpdb->get_row('SELECT * FROM '.GTLM_Analytics_DB::events_table().' ORDER BY id DESC LIMIT 1',ARRAY_A);page_check($e['source']==='source.example.org'&&$e['page']==='https://source.example.org/first%20post/'&&!str_contains(json_encode($e),'private@')&&!str_contains(json_encode($e),'secret'),'Event stores stripped page without sensitive URL fields',$e);
$_SERVER['HTTP_REFERER']='https://source.example.org/second-post/';GTLM_Analytics_Collector::collect($link,302,null);GTLM_Analytics::process();$r=GTLM_Analytics_Controller::report(['link_id'=>$id]);page_check($r['total']===3&&array_sum(array_column($r['pages'],'clicks'))===3&&in_array('https://source.example.org/first%20post/',array_column($r['pages'],'value'),true),'Page breakdown reconciles new and historical clicks',$r['pages']);
$second=$db->insert_link(['name'=>'Other referrer fixture','slug'=>'other-referrer-fixture','url'=>home_url('/target')]);GTLM_Analytics_Collector::collect($db->get_link_by_id($second),302,null);GTLM_Analytics::process();$r=GTLM_Analytics_Controller::report(['link_id'=>$id]);page_check($r['total']===3&&array_sum(array_column($r['pages'],'clicks'))===3,'Selected-link page report excludes other links');
for($i=0;$i<105;$i++){$_SERVER['HTTP_REFERER']='https://source.example.org/post-'.$i.'/';GTLM_Analytics_Collector::collect($link,302,null);}
$gen=GTLM_Analytics::config()['generation'];$db->lock();$db->aggregate_batch($gen,gmdate('Y-m-d H:i:s',time()-86400),50);$db->aggregate_batch($gen,gmdate('Y-m-d H:i:s',time()-86400),50);$db->unlock();GTLM_Analytics::process();
$count=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(DISTINCT value) FROM '.GTLM_Analytics_DB::hourly_table()." WHERE link_id=%d AND dimension='page' AND value<>'' AND value<>'_other'",$id));page_check($count===100,'Page cardinality stays bounded across batches',$count);
$filters=GTLM_Analytics_Controller::filters(['link_id'=>$id]);$db->start_export();$export=$db->export_page($filters,[]);$db->finish_export();page_check(count(array_filter($export,fn($r)=>$r['dimension']==='page'&&str_starts_with($r['value'],'https://source.example.org/')))>0,'CSV data includes the referring-page dimension');
$post=wp_insert_post(['post_title'=>'Published referrer fixture','post_name'=>'published-referrer-fixture','post_status'=>'publish','post_type'=>'post']);$url=get_permalink($post);$method=(new ReflectionClass(GTLM_Analytics_View::class))->getMethod('page_label');$label=$method->invoke(null,$url);page_check($label['label']==='Published referrer fixture'&&$label['description']===$url,'Admin page label resolves a published WordPress post');wp_update_post(['ID'=>$post,'post_status'=>'private']);$label=$method->invoke(null,$url);page_check($label['label']===$url&&!isset($label['description']),'Private post titles are not disclosed');wp_delete_post($post,true);
$db->delete_link($id);$db->delete_link($second);GTLM_Analytics::delete();$out=['passed'=>count(array_filter($checks,fn($r)=>$r['ok'])),'checks'=>$checks,'failed'=>array_values(array_filter($checks,fn($r)=>!$r['ok']))];echo json_encode($out,JSON_PRETTY_PRINT);exit($out['failed']?1:0);
