<?php
/** Complete referring-page listing checks in a disposable fixture. */
if(!defined('GTLM_TEST_FIXTURE')||!GTLM_TEST_FIXTURE||!str_starts_with(DB_NAME,'gtlm_test_'))exit(2);
require_once GTLM_PATH.'includes/class-gtlm-analytics.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-controller.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-view.php';require_once GTLM_PATH.'includes/class-gt-link-import.php';require_once GTLM_PATH.'includes/class-gt-link-admin-pages.php';require_once ABSPATH.'wp-admin/includes/template.php';
$checks=[];function pagination_check($ok,$label,$details=null){global$checks;$checks[]=['ok'=>(bool)$ok,'check'=>$label,'details'=>$ok?null:$details];}
$db=new GTLM_Analytics_DB();global$wpdb;GTLM_Analytics::delete();GTLM_Analytics::enable();$gen=GTLM_Analytics::config()['generation'];
$cat=$db->insert_category(['name'=>'Pagination fixture','slug'=>'pagination-fixture']);$id=$db->insert_link(['name'=>'Many referrers','slug'=>'many-referrers','url'=>home_url('/target'),'category_id'=>$cat]);$other=$db->insert_link(['name'=>'Other referrers','slug'=>'other-referrers','url'=>home_url('/target')]);
function page_event($id,$page){global$db,$gen;$db->append(['link_id'=>$id,'occurred_at'=>gmdate('Y-m-d H:i:s'),'generation'=>$gen,'source'=>'pages.example.org','page'=>$page,'country'=>'IN','device'=>'desktop','browser'=>'chrome','os'=>'linux','campaign'=>0,'status'=>302,'mode'=>'standard','geo'=>'off']);}
for($i=0;$i<55;$i++)page_event($id,'https://pages.example.org/page-'.str_pad((string)$i,3,'0',STR_PAD_LEFT).'/');
for($i=0;$i<3;$i++)page_event($id,'');page_event($other,'https://pages.example.org/other/');GTLM_Analytics::process();
// A historical total has no page dimension: merge it into the same unavailable entry once.
$bucket=gmdate('Y-m-d H:i:00');$wpdb->query($wpdb->prepare('INSERT INTO '.GTLM_Analytics_DB::hourly_table()." (link_id,bucket_start,dimension,value,clicks) VALUES(%d,%s,'total','',4) ON DUPLICATE KEY UPDATE clicks=clicks+4",$id,$bucket));
$seen=[];$sum=0;$first=null;
for($n=1;$n<=3;$n++){$r=GTLM_Analytics_Controller::pages(['link_id'=>$id,'sources_page'=>$n]);if(!$first)$first=$r;$seen=array_merge($seen,array_column($r['rows'],'value'));$sum+=array_sum(array_column($r['rows'],'clicks'));pagination_check(count($r['rows'])===($n===3?16:20),'Every result page has the expected bounded rows '.$n,$r);}
pagination_check(count($seen)===56&&count(array_unique($seen))===56&&$sum===62,'All retained entries are reachable once and their counts reconcile');pagination_check($first['pagination']['total_items']===56&&$first['pagination']['total_pages']===3,'Pagination reports the full result count');pagination_check($first['rows'][0]===['value'=>'','clicks'=>'7'],'Unknown and pre-attribution history form one entry');
$r=GTLM_Analytics_Controller::pages(['category_id'=>$cat,'sources_page'=>2]);pagination_check($r['pagination']['total_items']===56&&!in_array('https://pages.example.org/other/',array_column($r['rows'],'value'),true),'Category filtering applies to count and page rows');
$r=GTLM_Analytics_Controller::report(['link_id'=>$id,'sources_page'=>3]);pagination_check(count($r['pages'])===16&&$r['pages_pagination']['total_items']===56,'Summary API exposes all result pages and metadata');
$r=GTLM_Analytics_Controller::pages(['link_id'=>$id,'sources_page'=>999999999]);pagination_check($r['pagination']['current_page']===3&&!$r['pagination']['has_next'],'Out-of-range requests clamp before computing an offset');
foreach([0,-1,'2.5','bad',[],true] as $bad){pagination_check(is_wp_error(GTLM_Analytics_Controller::filters(['sources_page'=>$bad])),'Invalid result page is rejected');}
$r=GTLM_Analytics_Controller::pages(['link_id'=>999999]);pagination_check($r['rows']===[]&&$r['pagination']['total_items']===0&&$r['pagination']['from']===0,'Empty selections have accurate pagination');
foreach([10,50,100] as $size){$entries=[];$first_page=GTLM_Analytics_Controller::pages(['link_id'=>$id,'sources_per_page'=>$size]);for($n=1;$n<=$first_page['pagination']['total_pages'];$n++){$part=GTLM_Analytics_Controller::pages(['link_id'=>$id,'sources_per_page'=>$size,'sources_page'=>$n]);$entries=array_merge($entries,$part['rows']);}pagination_check(count($first_page['rows'])===min(56,$size)&&$first_page['pagination']['per_page']===$size&&count($entries)===56&&count(array_unique(array_column($entries,'value')))===56&&array_sum(array_column($entries,'clicks'))===62,'Chosen row count preserves the complete report: '.$size);}
$invalid_sizes=[0,-1,1,200,'20.5','bad',[],true];$sizes_rejected=true;foreach($invalid_sizes as $size){$sizes_rejected=$sizes_rejected&&is_wp_error(GTLM_Analytics_Controller::filters(['sources_per_page'=>$size]));}pagination_check($sizes_rejected,'Unsupported row counts are rejected');
wp_set_current_user(1);$_GET=['view'=>'pages','link_id'=>(string)$id,'sources_page'=>'2'];ob_start();GTLM_Analytics_View::render();$html=ob_get_clean();pagination_check(str_contains($html,'Showing 21–40 of 56')&&str_contains($html,'sources_page=3')&&str_contains($html,'name="view" value="pages"')&&!str_contains($html,'gtlm-analytics-chart'),'Dedicated listing includes pagination and preserves its view');
$_GET=['view'=>'pages','link_id'=>(string)$id,'sources_page'=>'2','sources_per_page'=>'10'];ob_start();GTLM_Analytics_View::render();$html=ob_get_clean();preg_match('/<form method="get" class="gtlm-pages-size">(.*?)<\/form>/s',$html,$size_form);pagination_check(str_contains($html,'Showing 11–20 of 56')&&str_contains($html,'sources_per_page=10')&&str_contains($html,'name="sources_per_page" value="10"')&&!str_contains($size_form[1]??'','name="sources_page"'),'Page size survives navigation and filter forms; resizing resets the result page');
$_GET=['view'=>'overview','link_id'=>(string)$id];ob_start();GTLM_Analytics_View::render();$html=ob_get_clean();pagination_check(!str_contains($html,'id="gtlm-referring-pages"')&&str_contains($html,'view=pages'),'Overview links to the separate page rather than embedding a truncated table');
$_GET=['page'=>'gtlm-links-settings'];$s=GTLM_Settings::get_instance();$view=new GTLM_Admin_Pages($db,$s,new GTLM_Import($db,$s));ob_start();$view->render_settings_page();$html=ob_get_clean();preg_match('/<textarea id="gtlm-ai-prompt"[^>]*>(.*?)<\/textarea>/s',$html,$matches);$prompt=html_entity_decode($matches[1]??'');pagination_check(str_contains($prompt,home_url('/'))&&str_contains($prompt,'https://gauravtiwari.org/gt-link-manager-rest-api-guide-ai-tools/')&&str_contains($prompt,'Ask only for missing information')&&str_contains($prompt,'read-only requests'),'Setup prompt includes this site, the guide and missing-detail instructions');pagination_check(str_contains($html,'id="gtlm-copy-ai-prompt"')&&str_contains($html,'role="status"'),'Copy prompt has a labelled action and accessible feedback');
$db->delete_link($id);$db->delete_link($other);$wpdb->delete(GTLM_DB::categories_table(),['id'=>$cat],['%d']);GTLM_Analytics::delete();$out=['passed'=>count(array_filter($checks,fn($c)=>$c['ok'])),'checks'=>$checks,'failed'=>array_values(array_filter($checks,fn($c)=>!$c['ok']))];echo json_encode($out,JSON_PRETTY_PRINT);exit($out['failed']?1:0);
