<?php
if(!defined('GTLM_TEST_FIXTURE')||!GTLM_TEST_FIXTURE||!str_starts_with(DB_NAME,'gtlm_test_'))exit(2);
require_once GTLM_PATH.'includes/class-gtlm-analytics.php';require_once GTLM_PATH.'includes/class-gtlm-analytics-controller.php';
$checks=[];function time_check($ok,$label,$data=null){global$checks;$checks[]=['ok'=>(bool)$ok,'check'=>$label,'details'=>$ok?null:$data];}
$db=new GTLM_Analytics_DB();GTLM_Analytics::delete();$r=GTLM_Analytics::enable();if(is_wp_error($r))throw new RuntimeException($r->get_error_message());
$tz_before=get_option('timezone_string');$offset_before=get_option('gmt_offset');$id=$db->insert_link(['name'=>'Timezone fixture','slug'=>'timezone-fixture','url'=>home_url('/target')]);$generation=GTLM_Analytics::config()['generation'];
function seed_time($id,$time,$source='time.example.org'){global$db,$generation;$db->append(['link_id'=>$id,'occurred_at'=>$time,'generation'=>$generation,'source'=>$source,'country'=>'','device'=>'desktop','browser'=>'chrome','os'=>'linux','campaign'=>0,'status'=>302,'mode'=>'standard','geo'=>'off']);}
// Kolkata midnight occurs at 18:30 UTC. Adjacent minute buckets must remain distinct.
update_option('timezone_string','Asia/Kolkata');$date=current_datetime()->modify('-1 day')->format('Y-m-d');$local_start=new DateTimeImmutable($date,wp_timezone());$utc_start=$local_start->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');
seed_time($id,gmdate('Y-m-d H:i:s',strtotime($utc_start.' UTC')-1));seed_time($id,$utc_start);seed_time($id,gmdate('Y-m-d H:i:s',strtotime($utc_start.' UTC')+60));GTLM_Analytics::process();
$f=GTLM_Analytics_Controller::filters(['from'=>$date,'to'=>$date,'link_id'=>$id,'granularity'=>'hour']);$r=$db->report($f);time_check($f['from_utc']===$utc_start,'Filters start at WordPress midnight',$f);time_check($r['total']===2&&count($r['trend'])===1&&str_contains($r['trend'][0]['day'],'00:00:00 +05:30'),'Kolkata minute boundary and local hour grouping',$r);
time_check(str_ends_with(GTLM_Analytics::status()['last_processed_at'],'+05:30'),'Status timestamp uses WP offset');
update_option('timezone_string','');update_option('gmt_offset',5.5);$f=GTLM_Analytics_Controller::filters(['from'=>$date,'to'=>$date,'link_id'=>$id,'granularity'=>'hour']);$r=$db->report($f);time_check($f['from_utc']===$utc_start&&$r['total']===2&&wp_timezone_string()==='+05:30','Numeric WordPress GMT offset uses local midnight and grouping',$r);
update_option('timezone_string','Asia/Kathmandu');$f=GTLM_Analytics_Controller::filters(['from'=>$date,'to'=>$date,'link_id'=>$id,'granularity'=>'hour']);$r=$db->report($f);time_check($r['total']===3&&str_contains($r['trend'][0]['day'],'+05:45'),'Existing rollups regroup after fractional timezone change',$r);
// Historical DST test uses the internal bounded DB API, independent of the UI's rolling 90-day limit.
update_option('timezone_string','America/New_York');seed_time($id,'2026-11-01 05:30:00');seed_time($id,'2026-11-01 06:30:00');$db->lock();$db->aggregate_batch($generation,'2026-01-01 00:00:00');$db->unlock();
$r=$db->report(['from_utc'=>'2026-11-01 04:00:00','to_utc'=>'2026-11-02 05:00:00','dimension'=>'source','granularity'=>'hour','link_id'=>$id,'category_id'=>0]);$labels=array_column($r['trend'],'day');time_check($r['total']===2&&count($labels)===2&&str_contains($labels[0],'-04:00')&&str_contains($labels[1],'-05:00'),'DST repeated hour stays distinct and chronological',$r);
seed_time($id,'2026-03-08 06:59:00');seed_time($id,'2026-03-08 07:00:00');$db->lock();$db->aggregate_batch($generation,'2026-01-01 00:00:00');$db->unlock();$r=$db->report(['from_utc'=>'2026-03-08 05:00:00','to_utc'=>'2026-03-09 04:00:00','dimension'=>'source','granularity'=>'hour','link_id'=>$id,'category_id'=>0]);$labels=array_column($r['trend'],'day');time_check(count($labels)===2&&str_contains($labels[0],'01:00:00 -05:00')&&str_contains($labels[1],'03:00:00 -04:00'),'DST spring gap is not fabricated',$r);
update_option('timezone_string',$tz_before);update_option('gmt_offset',$offset_before);$db->delete_link($id);GTLM_Analytics::delete();$out=['passed'=>count(array_filter($checks,fn($c)=>$c['ok'])),'checks'=>$checks,'failed'=>array_values(array_filter($checks,fn($c)=>!$c['ok']))];echo json_encode($out,JSON_PRETTY_PRINT);exit($out['failed']?1:0);
